name = "SymbolicTensors"
uuid = "2ae428ce-917c-11ea-3b8a-096394e63791"
authors = ["Robert Rosati", "UT-Austin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
