name = "SymbolicTensors"
uuid = "2ae428ce-917c-11ea-3b8a-096394e63791"
authors = ["Robert Rosati", "UT-Austin"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
julia = "1"
SymPy = "1.0"
PyCall = "1.91"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
